---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 27015, host: 27015}]
    - ["forwarded_port", {guest: 27020, host: 27020}]
    - ["private_network", {ip: "192.168.33.33"}]
  
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list: recipe[steamcmd::default]
    attributes:
  - name: counterstrike_source
    run_list: recipe[steamcmd::counterstrike_source]
    attributes:
